POST http://localhost:3000/auth/id?verifyCommit=false
Content-Type: application/json

{
  "principalId": "e6d046a2-449e-43ac-9d1a-5ad8ebd3391f",
  "resourceId": "f82523fa-34c7-41b3-b730-db19ee936958"
}

###
POST http://localhost:3000/auth/id?verifyCommit=true
Content-Type: application/json

{
  "principalId": "e6d046a2-449e-43ac-9d1a-5ad8ebd3391f",
  "resourceId": "f82523fa-34c7-41b3-b730-db19ee936958"
}

###
