POST http://localhost:3000/auth/id?verifyCommit=false
Content-Type: application/json

{
  "principalId": "3281ee12-d723-4077-ad0c-87ef5e993fdd",
  "resourceId": "a76a8df4-aa0e-41be-8b47-f0003fb7f60a"
}

###
POST http://localhost:3000/auth/id?verifyCommit=true
Content-Type: application/json

{
  "principalId": "3281ee12-d723-4077-ad0c-87ef5e993fdd",
  "resourceId": "a76a8df4-aa0e-41be-8b47-f0003fb7f60a"
}

###
