# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.companyABC.com:
    container_name: orderer0.companyABC.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer0.companyABC.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer0.companyABC.com/tls:/var/hyperledger/orderer/tls
        - orderer0.companyABC.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.companyABC.com:
    container_name: orderer1.companyABC.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer1.companyABC.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer1.companyABC.com/tls:/var/hyperledger/orderer/tls
      - orderer1.companyABC.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer2.companyABC.com:
    container_name: orderer2.companyABC.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer2.companyABC.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/companyABC.com/orderers/orderer2.companyABC.com/tls:/var/hyperledger/orderer/tls
      - orderer2.companyABC.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  peer0.org1.companyABC.com:
    container_name: peer0.org1.companyABC.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.companyABC.com
      - CORE_PEER_ADDRESS=peer0.org1.companyABC.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.companyABC.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.companyABC.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.companyABC.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.companyABC.com/peers/peer0.org1.companyABC.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.companyABC.com/peers/peer0.org1.companyABC.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.companyABC.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.companyABC.com:
    container_name: peer1.org1.companyABC.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.companyABC.com
      - CORE_PEER_ADDRESS=peer1.org1.companyABC.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.companyABC.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.companyABC.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.companyABC.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.companyABC.com/peers/peer1.org1.companyABC.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.companyABC.com/peers/peer1.org1.companyABC.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.companyABC.com:/var/hyperledger/production

    ports:
      - 8051:8051
